name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: See if curl works
      run: curl 'https://diff-data.com/build?image=library/hello-world:latest'
