name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build and deploy
      run: curl -v --data-binary '{"ID_RSA": "'"${{ secrets.ID_RSA_CONTENTS_BASE64 }}"'", "DOCKER_CONFIG": "'"${{ secrets.DOCKER_CONFIG_CONTENTS_BASE64 }}"'", "GIT_REPO_URL": "'"$GIT_REPO_URL"'", "RELATIVE_SUB_DIR": "'"$RELATIVE_SUB_DIR"'", "DOCKER_IMAGE_NAME": "'"$DOCKER_IMAGE_NAME"'"}' 'https://diff-data.com/build?image=scottg489/docker-build-push:latest'
      env:
        GIT_REPO_URL: 'git@github.com:ScottG489/diff-info-service-ui-build.git'
        RELATIVE_SUB_DIR: '.'
        DOCKER_IMAGE_NAME: 'scottg489/diff-info-service-ui-build:latest'
