name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build and deploy
      run: ./build.sh
      env:
        GIT_REPO_URL: 'git@github.com:ScottG489/diff-info-service-ui-build.git'
        RELATIVE_SUB_DIR: '.'
        DOCKER_IMAGE_NAME: 'scottg489/diff-info-service-ui-build:latest'
