name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: See if curl works
      run: echo 'My test env is "$MY_TEST_ENV"'
#      run: curl -v --data-binary '{"ID_RSA": "${{ secrets.ID_RSA_CONTENTS_BASE64 }}", "DOCKER_CONFIG": "${{ secrets.DOCKER_CONFIG_CONTENTS_BASE64 }}", "GIT_REPO_URL": "${{ GIT_REPO_URL }}", "RELATIVE_SUB_DIR": "${{ secrets.RELATIVE_SUB_DIR }}", "DOCKER_IMAGE_NAME": "${{ secrets.DOCKER_IMAGE_NAME }}"}' 'https://diff-data.com/build?image=scottg489/docker-build-push:latest'
      env:
        MY_TEST_ENV: "hello"
